apiVersion: v1
kind: ConfigMap
metadata:
  name: database-server-config
  namespace: database
data:
  servers: http://database-server-0.database-server.database.svc.cluster.local:5000,http://database-server-1.database-server.database.svc.cluster.local:5000,http://database-server-2.database-server.database.svc.cluster.local:5000
