apiVersion: v1
kind: Service
metadata:
  name: database-service-external
  namespace: database
spec:
  selector:
    app: database-server
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: database-server
  namespace: database
spec:
  selector:
    app: database-server
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  clusterIP: None  # Headless service for direct pod-to-pod communication
