apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-server
  namespace: database
spec:
  replicas: 3
  serviceName: database-server
  selector:
    matchLabels:
      app: database-server
  template:
    metadata:
      labels:
        app: database-server
    spec:
      containers:
      - name: database-server
        image: chandrakanthchalla11/database-image:v2.0.34
        ports:
        - containerPort: 5000
        env:
        - name: PEERS
          valueFrom:
            configMapKeyRef:
              name: database-server-config
              key: servers
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        readinessProbe:
          httpGet:
            path: /liveness
            port: 5000
          initialDelaySeconds: 5  # Delay before the probe starts
          periodSeconds: 10       # Frequency of the probe
          timeoutSeconds: 5       # Timeout for each probe
          failureThreshold: 3     # Number of failures before marking "not ready"

