apiVersion: v1
kind: Service
metadata:
  name: auction-service-external
  namespace: auction-service
spec:
  selector:
    app: auction-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
